# Generated by Django 4.1.3 on 2022-11-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWJTM', '0003_alter_tmusersdata_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmusersdata',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
