# Generated by Django 4.1.3 on 2022-11-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TWJTM', '0005_alter_tmusersdata_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmusersdata',
            name='photo',
        ),
    ]
