# Generated by Django 4.1.3 on 2022-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWJTM', '0010_alter_tmusersdata_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmusersdata',
            name='userid',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
