# Generated by Django 4.1.3 on 2022-12-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TWJTM', '0013_usersdata_delete_tmusersdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdata',
            name='userid',
        ),
    ]
