# Generated by Django 4.1.3 on 2022-12-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWJTM', '0015_tmusersdata_delete_usersdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmusersdata',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
