# Generated by Django 4.1.3 on 2022-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWJTM', '0016_tmusersdata_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80)),
                ('task', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('estimated_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Comments', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=80, null=True)),
                ('company', models.CharField(max_length=80)),
            ],
        ),
    ]
