# Generated by Django 4.1.3 on 2023-01-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TWJTM', '0017_taskdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdata',
            old_name='Comments',
            new_name='comments',
        ),
    ]
